import 'dotenv/config'
import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';
import path from 'path'
import { fileURLToPath } from 'url'
import fs from 'fs'

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const __siteroot = __dirname.replace("/catalogs", "");
const __target = "/src/_data/catalog/";

async function run() {
  try {
    // Check if environment variables are set
    if (!process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL) {
      throw new Error("GOOGLE_SERVICE_ACCOUNT_EMAIL environment variable is not set");
    }
    if (!process.env.GOOGLE_PRIVATE_KEY) {
      throw new Error("GOOGLE_PRIVATE_KEY environment variable is not set");
    }
    if (!process.env.FILAMENTS_SHEET_ID) {
      throw new Error("FILAMENTS_SHEET_ID environment variable is not set");
    }
    console.log("Environment variables check: GOOGLE_SERVICE_ACCOUNT_EMAIL, GOOGLE_PRIVATE_KEY, and FILAMENTS_SHEET_ID are set");

    // Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
    const serviceAccountAuth = new JWT({
      // env var values here are copied from service account credentials generated by google
      // see "Authentication" section in docs for more info
      email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
      key: process.env.GOOGLE_PRIVATE_KEY,
      scopes: ['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive.file'],
    })

    const filaments = new GoogleSpreadsheet(process.env.FILAMENTS_SHEET_ID, serviceAccountAuth)

    await filaments.loadInfo() // loads document properties and worksheets
    const filamentsSheet = filaments.sheetsByTitle['Filaments'] // or use `doc.sheetsById[id]` or `doc.sheetsByTitle[title]`
    const allFilaments = await filamentsSheet.getRows()
    const jsonArr = []

    for (var i = 0; i < allFilaments.length; i++) {
      jsonArr.push({
        filament: allFilaments[i].get("Filament"),
        baseColor: allFilaments[i].get("Base Color"),
        color: allFilaments[i].get("Color"),
        brand: allFilaments[i].get("Brand"),
        identifier: allFilaments[i].get("Identifier"),
        activeSpool: allFilaments[i].get("Active Spool (g)"),
        spareSpools: allFilaments[i].get("Spare Spools"),
        link: allFilaments[i].get("Link"),
        picture: allFilaments[i].get("Picture")
      })
    }

    fs.writeFile(
      __siteroot + __target + 'filaments.json',
      JSON.stringify(jsonArr),
      function(err) {
        if (err) {
          console.log(err)
        }
      }
    )
    console.log("Filaments catalog data generated successfully");
  } catch (error) {
    console.error("Error generating filaments catalog data:", error);
    process.exit(1);
  }
}

run();
