import 'dotenv/config'
import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';
import path from 'path'
import { fileURLToPath } from 'url'
import fs from 'fs'

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename)
const __siteroot = __dirname.replace('/cli/backlogs', '');
const __target = '/src/_data/backlogs/'

// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
  key: process.env.GOOGLE_PRIVATE_KEY,
  scopes: ['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive.file'],
})

const books = new GoogleSpreadsheet(process.env.BOOKS_SHEET_ID, serviceAccountAuth)

await books.loadInfo() // loads document properties and worksheets
const booksSheet = books.sheetsByTitle['Books'] // or use `doc.sheetsById[id]` or `doc.sheetsByTitle[title]`
const allBooks = await booksSheet.getRows()
const jsonArr = []
for (var i = 0; i < allBooks.length; i++) {
  jsonArr.push({
    title: allBooks[i].get("Title"),
    authorFirst: allBooks[i].get("Author First"),
    authorLast: allBooks[i].get("Author Last"),
    genre: allBooks[i].get("Genre"),
    series: allBooks[i].get("Series"),
    owned: allBooks[i].get("Owned?"),
    read: allBooks[i].get("Read?"),
    compDate: allBooks[i].get("Comp Date"),
    status: allBooks[i].get("Status"),
    information: allBooks[i].get("Information"),
    pages: allBooks[i].get("Pages"),
  })
}
// console.log(allBooks[8]._rawData.slice(0,10))
const __targetFile = 'books.json'
fs.writeFile(__siteroot + __target + __targetFile, JSON.stringify(jsonArr), function(err) {
  if (err) {
    console.log(err)
  }
})