import 'dotenv/config'
import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';
import path from 'path'
import { fileURLToPath } from 'url'
import fs from 'fs'

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename)
const __siteroot = __dirname.replace('/cli/backlogs', '');
const __target = '/src/_data/backlogs/'

// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
  key: process.env.GOOGLE_PRIVATE_KEY,
  scopes: ['https://www.googleapis.com/auth/spreadsheets'],
})

const games = new GoogleSpreadsheet(process.env.GAMES_SHEET_ID, serviceAccountAuth)

await games.loadInfo() // loads document properties and worksheets
const gamesSheet = games.sheetsByTitle['Master List'] // or use `doc.sheetsById[id]` or `doc.sheetsByTitle[title]`
const allGames = await gamesSheet.getRows()
const beatenArr = []
const progressArr = []
const priorityArr = []
for (var i = 0; i < allGames.length; i++) {
  var data = {
    title: allGames[i]._rawData[0],
    series: allGames[i]._rawData[1],
    seriesOrder: allGames[i]._rawData[2],
    system: allGames[i]._rawData[4],
    hrEst: allGames[i]._rawData[5],
    owned: allGames[i]._rawData[6],
    status: allGames[i]._rawData[7],
    compDate: allGames[i]._rawData[8],
    hrComp: allGames[i]._rawData[9],
    information: allGames[i]._rawData[10],
  }

  if (["In Progress"].includes(data.status)) {progressArr.push(data)}
  if (["Installed", "Priority"].includes(data.status)) {priorityArr.push(data)}
  if (data.compDate) {beatenArr.push(data)}
}
fs.writeFile(__siteroot + __target + 'gamesProgress.json', JSON.stringify(progressArr), function(err) {
  if (err) {
    console.log(err)
  }
})
fs.writeFile(__siteroot + __target + 'gamesPriority.json', JSON.stringify(priorityArr), function(err) {
  if (err) {
    console.log(err)
  }
})
const sortedArr = beatenArr.sort(function(a,b) {
  return Date.parse(b.compDate) - Date.parse(a.compDate)
})
fs.writeFile(__siteroot + __target + 'gamesBeaten.json', JSON.stringify(sortedArr), function(err) {
  if (err) {
    console.log(err)
  }
})