import 'dotenv/config'
import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';
import path from 'path'
import { fileURLToPath } from 'url'
import fs from 'fs'

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename)
const __siteroot = __dirname.replace('/cli/backlogs', '');
const __target = '/src/_data/catalog/'

// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
  key: process.env.GOOGLE_PRIVATE_KEY,
  scopes: ['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive.file'],
})

const keebs = new GoogleSpreadsheet('1RPeNzP2GJKgQhrghuuGK5W08biWI_t3us96oqGhz6U4', serviceAccountAuth)

await keebs.loadInfo() // loads document properties and worksheets
const keebsSheet = keebs.sheetsByTitle['Keyboards'] // or use `doc.sheetsById[id]` or `doc.sheetsByTitle[title]`
const allKeebs = await keebsSheet.getRows()
const jsonArr = []
for (var i = 0; i < allKeebs.length; i++) {
  if (allKeebs[i]._rawData[2] != 'Wishlist') {
    var switchArray = allKeebs[i]._rawData[7].split(' ')
    jsonArr.push({
      name: allKeebs[i]._rawData[0],
      url: allKeebs[i]._rawData[5],
      image: allKeebs[i]._rawData[10],
      switches: switchArray.slice(0, switchArray.length - 2).join(' '),
      keycaps: allKeebs[i]._rawData[8],
      size_type: allKeebs[i]._rawData[3],
      description: allKeebs[i]._rawData[9],
    })
  }
}
const __targetFile = 'keebs.json'
fs.writeFile(__siteroot + __target + __targetFile, JSON.stringify(jsonArr), function(err) {
  if (err) {
    console.log(err)
  }
})